### ISSUE TITLE
unable to mix multiple files

### ISSUE THREAD

**Issue by reneweteling** [joecohens/laravel-elixir-react#1]
Unable to mix multiple files

``` javascript
elixir(function(mix) {

    // jsx files
    mix.react('../jsx/network.jsx');
    mix.react('../jsx/messages.jsx');
}
```

This only generates the messages.js file. as you can see here

![screen shot 2015-02-26 at 10 35 13](https://cloud.githubusercontent.com/assets/3830933/6389313/32c47556-bda3-11e4-88bb-091756657e84.png)

if i only compile network, or messages they compile just fine. But im unable to compile them in 1 try

**Comment by joecohens** [comment]
Not sure about it but I think elixir only let's you run the function once. Nb, you may pass a path to a folder to the src instead of a single file. https://www.npmjs.com/package/react-tools

If you still have trouble let me know.

**Comment by reneweteling** [comment]
hey thanks

```
      // jsx files
      .react('../jsx/*.jsx');
```

this works
