### ISSUE TITLE
Use babel instead of react-tools?

### ISSUE THREAD

**Issue by 18601673727** [joecohens/laravel-elixir-react#6]
``` bash
$ npm install --save-dev laravel-elixir-react

npm WARN deprecated react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
```

**Comment by joecohens** [comment]
@18601673727 thanks! In that case maybe it would be better to deprecate this package since Laravel Elixir already support babel by default. See https://github.com/sindresorhus/gulp-react/issues/37 what do you think?

**Comment by 18601673727** [comment]
@joecohens Yeah, my opinion is just like yours.
