### ISSUE TITLE
Error: Cannot find module 'laravel-elixir/ingredients/commands/Utilities'

### ISSUE THREAD

**Issue by Jegulsky** [joecohens/laravel-elixir-react#8]
Error: Cannot find module 'laravel-elixir/ingredients/commands/Utilities'

**Comment by joecohens** [comment]
This package is Deprecated since you can use babel options directly on Elixir https://github.com/joecohens/laravel-elixir-react#deprecated-babel-is-now-included-on-elixir-by-default

**Comment by joecohens** [comment]
Also you can look at https://github.com/joecohens/laravel-elixir-react/issues/6
